; Textos propios de Fortuna Real para que una versión instalada no se confunda
; con una instalación nueva. Los nombres de estas cadenas forman parte de la
; plantilla NSIS oficial de Tauri.
LangString addOrReinstall ${LANG_SPANISH} "Actualizar o reparar esta instalación (conserva tus datos)"
LangString alreadyInstalled ${LANG_SPANISH} "Fortuna Real ya está instalado"
LangString alreadyInstalledLong ${LANG_SPANISH} "Fortuna Real ${VERSION} ya está instalado. Puedes reparar la instalación sin perder tus datos o desinstalar el programa."
LangString appRunning ${LANG_SPANISH} "Fortuna Real está abierto. Ciérralo antes de continuar."
LangString appRunningOkKill ${LANG_SPANISH} "Fortuna Real está abierto.$\nPulsa Aceptar para cerrarlo y continuar."
LangString chooseMaintenanceOption ${LANG_SPANISH} "Elige si deseas reparar o desinstalar esta versión."
LangString choowHowToInstall ${LANG_SPANISH} "Elige cómo deseas pasar a Fortuna Real ${VERSION}."
LangString createDesktop ${LANG_SPANISH} "Crear acceso directo en el escritorio"
LangString dontUninstall ${LANG_SPANISH} "Actualizar directamente y conservar mis datos (recomendado)"
LangString dontUninstallDowngrade ${LANG_SPANISH} "Conservar la versión más reciente (no se permite reemplazarla por una anterior)"
LangString failedToKillApp ${LANG_SPANISH} "No se pudo cerrar Fortuna Real. Ciérralo manualmente e inténtalo de nuevo."
LangString installingWebview2 ${LANG_SPANISH} "Preparando el componente visual de Fortuna Real..."
LangString newerVersionInstalled ${LANG_SPANISH} "Ya tienes una versión más reciente de Fortuna Real. Para evitar perder funciones, conserva la versión instalada."
LangString older ${LANG_SPANISH} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_SPANISH} "Hay una versión $R4 de Fortuna Real instalada. Puedes actualizarla conservando tus datos o retirar primero sus archivos e instalar la versión nueva."
LangString silentDowngrades ${LANG_SPANISH} "No se puede sustituir automáticamente una versión más reciente por una anterior.$\n"
LangString unableToUninstall ${LANG_SPANISH} "No se pudo retirar la versión anterior."
LangString uninstallApp ${LANG_SPANISH} "Desinstalar Fortuna Real"
LangString uninstallBeforeInstalling ${LANG_SPANISH} "Desinstalar la versión anterior e instalar la nueva"
LangString unknown ${LANG_SPANISH} "desconocida"
LangString webview2AbortError ${LANG_SPANISH} "No se pudo preparar WebView2. Reinicia el instalador e inténtalo de nuevo."
LangString webview2DownloadError ${LANG_SPANISH} "Error al descargar WebView2: $0"
LangString webview2DownloadSuccess ${LANG_SPANISH} "WebView2 se descargó correctamente."
LangString webview2Downloading ${LANG_SPANISH} "Descargando WebView2..."
LangString webview2InstallError ${LANG_SPANISH} "No se pudo instalar WebView2. Código: $1."
LangString webview2InstallSuccess ${LANG_SPANISH} "WebView2 se instaló correctamente."
LangString deleteAppData ${LANG_SPANISH} "Eliminar también participantes, historial, premios y configuración"
